services:
  postgres:
    image: postgres:latest
    container_name: softplan_desafio_db
    restart: always
    environment:
      POSTGRES_DB: softplan_desafio
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5452:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
