services:
  api01: &api
    build:
      context: ./backend
      dockerfile: Dockerfile
    hostname: api01
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/softplan-desafio
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "180MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "180MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=softplan-desafio
    ports:
      - "5452:5432"
    command: postgres -c 'max_connections=450'
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "140MB"
          
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - nginx
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1